name: Build APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-cache-dependency-path: 'buildozer.spec'
    - name: Build with Buildozer
      uses: ArtemGovorov/buildozer-action@v1
      with:
        command: buildozer -v android debug
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
